# ********RoostGPT********

# Test generated by RoostGPT for test defaultIteration using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete Country by ID API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Delete country by ID with valid headers and path parameter
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method DELETE
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '##string'

    Examples:
      | read('country_id_delete.csv') |

  Scenario Outline: Delete country by ID with missing headers
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    When method DELETE
    Then status 401

    Examples:
      | id | app_identifier                                               |
      | 32 | d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d |

  Scenario Outline: Delete country by ID with invalid path parameter
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method DELETE
    Then status 404

    Examples:
      | id  | app_identifier                                               | customer_secret_key                                          |
      | 999 | d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d | 12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe |
