# ********RoostGPT********

# Test generated by RoostGPT for test defaultIteration using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Country API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    * header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'

  Scenario Outline: Get country by ID
    Given path 'country', <id>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data == '#object'
    And match response.data.country == '#object'
    And match response.data.country.id == '#number'
    And match response.data.country.name == '#string'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#[]'
    And match each response.data.country.currencies[*] == '#string'
    And match response.error_info == '#string'

    Examples:
      | read('country_id_get.csv') |
