
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanDeepSeek using AI Type deepseek_ai and AI Model deepseek-reasoner

Test generated by RoostGPT for test amanDeepSeek using AI Type deepseek_ai and AI Model deepseek-reasoner

ROOST_METHOD_HASH=findByText_9cfb3c8d1d
ROOST_METHOD_SIG_HASH=findByText_5b4ac37762

Here are the generated test scenarios for the `findByText` method:

---

**Scenario 1: Valid search text returns up to five posts sorted by experience**

**Details:**
  - TestName: findByTextWithValidQueryReturnsSortedAndLimitedPosts
  - Description: Validates that a non-empty search text triggers a MongoDB aggregation with the correct query, sorting, and limiting logic. Ensures the converter maps results to Post objects.
**Execution:**
  - Arrange: Mock `client` to return a database and collection. Stub `collection.aggregate()` to return a predefined set of documents. Mock `converter.read()` to return valid Post objects.
  - Act: Call `findByText("Java")`.
  - Assert: Verify the returned list has ≤5 Post objects sorted by `exp` ascending.
**Validation:**
  - Ensures the `$search`, `$sort`, and `$limit` stages are applied correctly. Confirms the method adheres to the expected search logic and result limits.

---

**Scenario 2: Empty search text executes query but returns no results**

**Details:**
  - TestName: findByTextWithEmptyQueryReturnsEmptyList
  - Description: Tests the behavior when the input text is an empty string. MongoDB may return no results for an empty query.
**Execution:**
  - Arrange: Mock `collection.aggregate()` to return an empty iterable.
  - Act: Call `findByText("")`.
  - Assert: Check the result is an empty list.
**Validation:**
  - Ensures the method does not throw errors for empty input and gracefully returns no results.

---

**Scenario 3: No matching documents return an empty list**

**Details:**
  - TestName: findByTextWithNoMatchesReturnsEmptyList
  - Description: Validates the method returns an empty list when no documents match the search text.
**Execution:**
  - Arrange: Configure `collection.aggregate()` to return zero documents.
  - Act: Call `findByText("NonexistentTerm")`.
  - Assert: Assert the result list has size 0.
**Validation:**
  - Confirms the method does not return null or invalid objects when no matches exist.

---

**Scenario 4: Aggregation result exceeding five documents is truncated**

**Details:**
  - TestName: findByTextWithMoreThanFiveMatchesLimitsResults
  - Description: Ensures the `$limit: 5` stage restricts results to five even if more matches exist.
**Execution:**
  - Arrange: Stub `collection.aggregate()` to return six documents.
  - Act: Call `findByText("CommonTerm")`.
  - Assert: Verify the result contains exactly five Post objects.
**Validation:**
  - Validates the `$limit` stage is applied to comply with business requirements.

---

**Scenario 5: Results are sorted by experience in ascending order**

**Details:**
  - TestName: findByTextResultsSortedByExperienceAscending
  - Description: Checks if documents are sorted by the `exp` field in ascending order.
**Execution:**
  - Arrange: Return documents with `exp: 2`, `exp: 1`, `exp: 3` and validate their order after sorting.
  - Act: Call `findByText("Test")`.
  - Assert: Confirm posts are ordered as `exp: 1`, `exp: 2`, `exp: 3`.
**Validation:**
  - Ensures sorting logic aligns with the `$sort: { exp: 1 }` stage.

---

**Scenario 6: Null search text throws NullPointerException**

**Details:**
  - TestName: findByTextWithNullQueryThrowsException
  - Description: Tests that passing `null` as the text input throws an exception due to invalid query construction.
**Execution:**
  - Arrange: No special setup required (depends on MongoDB driver behavior).
  - Act/Assert: Use `assertThrows` to check for `NullPointerException` or MongoDB errors.
**Validation:**
  - Ensures the method validates inputs or documents MongoDB’s handling of invalid queries.

---

**Scenario 7: Converter maps all result documents to Post objects**

**Details:**
  - TestName: findByTextConvertsAllDocumentsToPosts
  - Description: Validates that `converter.read()` is called once per document in the result.
**Execution:**
  - Arrange: Mock `collection.aggregate()` to return three documents.
  - Act: Call `findByText("Valid")`.
  - Assert: Verify `converter.read()` is invoked three times.
**Validation:**
  - Ensures the conversion process is correctly applied to all aggregated documents.

---

**Scenario 8: Search targets correct fields (techs, desc, profile)**

**Details:**
  - TestName: findByTextSearchesInSpecifiedFields
  - Description: Checks that the `$search` stage includes the fields `techs`, `desc`, and `profile`.
**Execution:**
  - Arrange: Capture the argument passed to `collection.aggregate()`.
  - Act: Call `findByText("React")`.
  - Assert: Validate the `$search` stage’s `path` array contains the correct fields.
**Validation:**
  - Confirms the search logic aligns with the requirement to query specific fields.

---

These scenarios cover core functionality, edge cases, and error conditions while adhering to the method’s structure and dependencies.,
*/

// ********RoostGPT********
package com.telusko.joblisting.repository;

import com.mongodb.client.AggregateIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.telusko.joblisting.model.Post;
import org.bson.Document;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.ArrayList;
import org.springframework.stereotype.Component;

class SearchRepositoryImplFindByTextTest {

	@Mock
	private MongoClient client;

	@Mock
	private MongoConverter converter;

	@Mock
	private MongoDatabase database;

	@Mock
	private MongoCollection<Document> collection;

	@Mock
	private AggregateIterable<Document> aggregateResult;

	@InjectMocks
	private SearchRepositoryImpl searchRepository;

	@Captor
	private ArgumentCaptor<List<Document>> pipelineCaptor;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		when(client.getDatabase("telusko")).thenReturn(database);
		when(database.getCollection("JobPost")).thenReturn(collection);
		when(collection.aggregate(any())).thenReturn(aggregateResult);
	}

	@Test
	@Tag("valid")
	void findByTextWithValidQueryReturnsSortedAndLimitedPosts() {
		Document doc1 = new Document("exp", 2);
		Document doc2 = new Document("exp", 1);
		when(aggregateResult.spliterator()).thenReturn(Arrays.<Document>asList(doc1, doc2).spliterator());
		when(converter.read(eq(Post.class), any())).thenReturn(new Post());

		List<Post> result = searchRepository.findByText("Java");

		assertTrue(result.size() <= 5);
		verify(collection).aggregate(pipelineCaptor.capture());
		List<Document> pipeline = pipelineCaptor.getValue();
		assertEquals(3, pipeline.size());
		assertEquals(1L, pipeline.get(1).get("$sort", Document.class).get("exp"));
	}

	@Test
    @Tag("invalid")
    void findByTextWithEmptyQueryReturnsEmptyList() {
        when(aggregateResult.spliterator()).thenReturn(Arrays.<Document>asList().spliterator());

        List<Post> result = searchRepository.findByText("");

        assertTrue(result.isEmpty());
    }

	@Test
	@Tag("boundary")
	void findByTextWithMoreThanFiveMatchesLimitsResults() {
		List<Document> sixDocs = Arrays.<Document>asList(new Document(), new Document(), new Document(), new Document(),
				new Document(), new Document());
		when(aggregateResult.spliterator()).thenReturn(sixDocs.spliterator());
		when(converter.read(eq(Post.class), any())).thenReturn(new Post());

		List<Post> result = searchRepository.findByText("CommonTerm");

		assertEquals(5, result.size());
	}

	@Test
	@Tag("valid")
	void findByTextResultsSortedByExperienceAscending() {
		Document doc1 = new Document("exp", 3);
		Document doc2 = new Document("exp", 1);
		Document doc3 = new Document("exp", 2);
		when(aggregateResult.spliterator()).thenReturn(Arrays.<Document>asList(doc1, doc2, doc3).spliterator());
		when(converter.read(eq(Post.class), any())).thenAnswer(inv -> {
			Document doc = inv.getArgument(1);
			Post post = new Post();
			post.setExp(doc.getInteger("exp"));
			return post;
		});

		List<Post> result = searchRepository.findByText("Test");

		assertEquals(1, result.get(0).getExp());
		assertEquals(2, result.get(1).getExp());
		assertEquals(3, result.get(2).getExp());
	}

	@Test
	@Tag("invalid")
	void findByTextWithNullQueryThrowsException() {
		assertThrows(NullPointerException.class, () -> searchRepository.findByText(null));
	}

	@Test
	@Tag("valid")
	void findByTextConvertsAllDocumentsToPosts() {
		List<Document> threeDocs = Arrays.<Document>asList(new Document(), new Document(), new Document());
		when(aggregateResult.spliterator()).thenReturn(threeDocs.spliterator());

		searchRepository.findByText("Valid");

		verify(converter, times(3)).read(eq(Post.class), any());
	}

	@Test
	@Tag("valid")
	void findByTextSearchesInSpecifiedFields() {
		searchRepository.findByText("React");

		verify(collection).aggregate(pipelineCaptor.capture());
		Document searchStage = pipelineCaptor.getValue().get(0);
		List<String> searchPaths = searchStage.get("$search", Document.class)
			.get("text", Document.class)
			.get("path", List.class);

		assertTrue(searchPaths.containsAll(Arrays.asList("techs", "desc", "profile")));
	}

}