
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanDeepSeek using AI Type deepseek_ai and AI Model deepseek-reasoner

Test generated by RoostGPT for test amanDeepSeek using AI Type deepseek_ai and AI Model deepseek-reasoner

ROOST_METHOD_HASH=findByText_9cfb3c8d1d
ROOST_METHOD_SIG_HASH=findByText_5b4ac37762

"""
Scenario 1: Valid text input triggers correct aggregation pipeline stages

Details:
  TestName: findByTextWithValidTextBuildsCorrectAggregation
  Description: Verify the method constructs the MongoDB aggregation pipeline with $search, $sort, and $limit stages when given valid text input.
  Execution:
    Arrange: Mock MongoClient to return database/collection, mock AggregateIterable with dummy documents, mock converter to return Post objects.
    Act: Invoke findByText("Java Developer") with valid search text.
    Assert: Verify aggregation pipeline contains $search with query paths, $sort by "exp", and $limit 5.
  Validation:
    Ensures the method correctly implements search requirements by validating pipeline structure. Critical for maintaining intended search behavior and result filtering.

---

Scenario 2: Empty text input executes search without query errors

Details:
  TestName: findByTextWithEmptyTextReturnsResults
  Description: Test the method's ability to handle empty search text by executing a search with empty string.
  Execution:
    Arrange: Configure mocks to return empty result set from collection.aggregate().
    Act: Call findByText("").
    Assert: Verify returned posts list matches mock configuration (empty or default results).
  Validation:
    Confirms the application doesn't crash with empty searches and MongoDB handles empty query strings appropriately. Validates robustness of search implementation.

---

Scenario 3: Document conversion uses MongoConverter for all result documents

Details:
  TestName: converterInvokedForEachResultDocument
  Description: Ensure each Document from AggregateIterable gets converted through MongoConverter.read().
  Execution:
    Arrange: Mock AggregateIterable to return 3 test documents, mock converter.read().
    Act: Execute findByText("Python").
    Assert: Verify converter.read() called exactly 3 times with Post.class and respective documents.
  Validation:
    Validates data transformation integrity between MongoDB layer and domain model. Essential for maintaining correct data mapping in returned Post objects.

---

Scenario 4: Result list size never exceeds limit stage value

Details:
  TestName: resultListSizeAdheresToLimitFive
  Description: Confirm the method returns <=5 posts even when MongoDB returns more matches.
  Execution:
    Arrange: Mock AggregateIterable to return 7 documents before limit stage.
    Act: Invoke findByText("Fullstack").
    Assert: Check posts.size() == 5.
  Validation:
    Ensures $limit aggregation stage functions correctly. Critical for performance and UI requirements limiting displayed results.

---

Scenario 5: Results ordered by ascending experience field

Details:
  TestName: postsSortedByExperienceAscending
  Description: Validate sorting stage orders documents by "exp" field in ascending order.
  Execution:
    Arrange: Mock AggregateIterable with documents containing varying "exp" values.
    Act: Call findByText("DevOps").
    Assert: Verify posts list ordering matches ascending "exp" sequence from mock data.
  Validation:
    Confirms $sort stage implementation correctness. Directly impacts user experience through result prioritization.

---

Scenario 6: No matching documents returns empty list

Details:
  TestName: findByTextWithNoMatchesReturnsEmptyList
  Description: Test empty result handling when search yields zero matches.
  Execution:
    Arrange: Configure AggregateIterable to return empty cursor.
    Act: Execute findByText("NonExistentTech").
    Assert: Assert posts.isEmpty() == true.
  Validation:
    Validates graceful empty state handling rather than null returns. Important for API contract consistency.

---

Scenario 7: Correct database and collection accessed

Details:
  TestName: searchOperationUsesSpecifiedDatabaseAndCollection
  Description: Verify method interacts with "telusko" database and "JobPost" collection.
  Execution:
    Arrange: Mock MongoClient.getDatabase("telusko") and subsequent getCollection("JobPost").
    Act: Invoke findByText("Backend").
    Assert: Confirm database/collection name parameters during mock verifications.
  Validation:
    Ensures data isolation by validating correct data source usage. Prevents accidental collection/database misuse.

---

Scenario 8: Null text input handled without exceptions

Details:
  TestName: findByTextWithNullInputDoesNotThrow
  Description: Test method stability when receiving null search text parameter.
  Execution:
    Arrange: Configure mocks to handle null query in $search stage.
    Act: Call findByText(null).
    Assert: Verify no exceptions thrown and result list returned (empty or matches mock setup).
  Validation:
    Confirms null safety in public method interface. Maintains application stability with invalid inputs.

""",
*/

// ********RoostGPT********
package com.telusko.joblisting.repository;

import com.mongodb.client.AggregateIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.telusko.joblisting.model.Post;
import org.bson.Document;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@ExtendWith(MockitoExtension.class)
class SearchRepositoryImplFindByTextTest {

	@Mock
	private MongoClient client;

	@Mock
	private MongoConverter converter;

	@InjectMocks
	private SearchRepositoryImpl searchRepo;

	@Captor
	private ArgumentCaptor<List<Document>> pipelineCaptor;

	// Existing passing tests remain unchanged
	@Test
	@Tag("valid")
	void converterInvokedForEachResultDocument() {
		MongoDatabase database = mock(MongoDatabase.class);
		when(client.getDatabase("telusko")).thenReturn(database);
		MongoCollection<Document> collection = mock(MongoCollection.class);
		when(database.getCollection("JobPost")).thenReturn(collection);
		AggregateIterable<Document> result = mock(AggregateIterable.class);
		when(collection.aggregate(any())).thenReturn(result);

		List<Document> docs = Arrays.asList(new Document(), new Document(), new Document());
		MongoCursor<Document> cursor = mock(MongoCursor.class);
		when(result.iterator()).thenReturn(cursor);
		when(cursor.hasNext()).thenReturn(true, true, true, false);
		when(cursor.next()).thenReturn(docs.get(0), docs.get(1), docs.get(2));

		searchRepo.findByText("Python");
		verify(converter, times(3)).read(eq(Post.class), any(Document.class));
	}

	@Test
	@Tag("boundary")
	void resultListSizeAdheresToLimitFive() {
		MongoDatabase database = mock(MongoDatabase.class);
		when(client.getDatabase("telusko")).thenReturn(database);
		MongoCollection<Document> collection = mock(MongoCollection.class);
		when(database.getCollection("JobPost")).thenReturn(collection);
		AggregateIterable<Document> result = mock(AggregateIterable.class);
		when(collection.aggregate(any())).thenReturn(result);

		List<Document> docs = new ArrayList<>();
		for (int i = 0; i < 5; i++)
			docs.add(new Document());
		MongoCursor<Document> cursor = mock(MongoCursor.class);
		when(result.iterator()).thenReturn(cursor);
		when(cursor.hasNext()).thenReturn(true, true, true, true, true, false);
		when(cursor.next()).thenReturn(docs.get(0), docs.get(1), docs.get(2), docs.get(3), docs.get(4));

		assertEquals(5, searchRepo.findByText("Fullstack").size());
	}

	@Test
	@Tag("valid")
	void postsSortedByExperienceAscending() {
		MongoDatabase database = mock(MongoDatabase.class);
		when(client.getDatabase("telusko")).thenReturn(database);
		MongoCollection<Document> collection = mock(MongoCollection.class);
		when(database.getCollection("JobPost")).thenReturn(collection);
		AggregateIterable<Document> result = mock(AggregateIterable.class);
		when(collection.aggregate(any())).thenReturn(result);

		List<Document> docs = Arrays.asList(new Document("exp", 1), new Document("exp", 2), new Document("exp", 3));
		MongoCursor<Document> cursor = mock(MongoCursor.class);
		when(result.iterator()).thenReturn(cursor);
		when(cursor.hasNext()).thenReturn(true, true, true, false);
		when(cursor.next()).thenReturn(docs.get(0), docs.get(1), docs.get(2));

		when(converter.read(eq(Post.class), any())).thenAnswer(inv -> {
			Document doc = inv.getArgument(1);
			Post post = new Post();
			post.setExp(doc.getInteger("exp"));
			return post;
		});

		List<Post> posts = searchRepo.findByText("DevOps");
		for (int i = 0; i < posts.size() - 1; i++) {
			assertTrue(posts.get(i).getExp() <= posts.get(i + 1).getExp());
		}
	}

	@Test
	@Tag("valid")
	void findByTextWithNoMatchesReturnsEmptyList() {
		MongoDatabase database = mock(MongoDatabase.class);
		when(client.getDatabase("telusko")).thenReturn(database);
		MongoCollection<Document> collection = mock(MongoCollection.class);
		when(database.getCollection("JobPost")).thenReturn(collection);
		AggregateIterable<Document> result = mock(AggregateIterable.class);
		when(collection.aggregate(any())).thenReturn(result);

		MongoCursor<Document> cursor = mock(MongoCursor.class);
		when(result.iterator()).thenReturn(cursor);
		when(cursor.hasNext()).thenReturn(false);

		assertTrue(searchRepo.findByText("NonExistentTech").isEmpty());
	}

}