// Test generated by RoostGPT for test aman-sampletest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.controller;

import org.junit.Test;
import org.mockito.Mockito;
import org.springframework.mock.web.MockHttpServletResponse;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class PostController_redirect_31b271143a_Test {

    @Test
    public void testRedirectSuccess() throws IOException {
        HttpServletResponse response = new MockHttpServletResponse();
        PostController controller = new PostController();
        controller.redirect(response);
        Mockito.verify(response).sendRedirect("/swagger-ui.html");
    }

    @Test(expected = IOException.class)
    public void testRedirectFailure() throws IOException {
        HttpServletResponse response = Mockito.mock(HttpServletResponse.class);
        Mockito.doThrow(new IOException()).when(response).sendRedirect("/swagger-ui.html");
        PostController controller = new PostController();
        controller.redirect(response);
    }
}
