# ********RoostGPT********

# Test generated by RoostGPT for test amanKarate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /availabilityCheck_post for http method type POST 
# RoostTestHash=bc409fdb92
# 
# 

# ********RoostGPT********
Feature: Availability Check

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Check if the Availability Check Endpoint is working
    Given path '/availabilityCheck'
    And request <body>
    When method post
    Then status <status>
    And match $ == <expectedResponse>

    Examples:
      | body                                                                         | status | expectedResponse                                                       |
      | { "customer": { "subscriberId": "SVTL001" }, "address": { "id": 14393 }}     |    200 | { "control": { "type": "S", "code": "200", "message": "OK" }}          |
      | { "customer": { "subscriberId": "SVTL001" }, "address": { "id": 2449 }}      |    200 | { "control": { "type": "S", "code": "200", "message": "OK" }}          |
      | { "customer": { "subscriberId": "SVTL001" }, "address": { "id": 0 }}         |    400 | { "control": { "type": "E", "code": "400", "message": "Bad Request" }} |
      | { "customer": { "subscriberId": "SVTL001" }, "address": { "id": "invalid" }} |    400 | { "control": { "type": "E", "code": "400", "message": "Bad Request" }} |
      | { "customer": { "subscriberId": "invalid" }, "address": { "id": 2449 }}      |    400 | { "control": { "type": "E", "code": "400", "message": "Bad Request" }} |
