# ********RoostGPT********

# Test generated by RoostGPT for test amanKarate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /availabilityCheck_post for http method type POST 
# RoostTestHash=11e354dac0
# 
# 

# ********RoostGPT********
Feature: Availability Check API

  Background:
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')

  Scenario Outline: Post availability check
    Given url urlBase + '/availabilityCheck'
    And request {}
    When method post
    Then status <status>
    And match response == <expectedResponse>

    Examples:
      | status | expectedResponse                                                                                                                                                                                                                                                                              |
      |    200 | { "control": { "type": "#string", "message": "#string", "code": "#string" }, "resource": { "resource": { "inventoryId": "#number", "maxBandwidth": "#number", "availabilityType": "#number", "availabilityCode": "#number", "availabilityDescription": "#string", "products": "#object" } } } |
      |    400 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    401 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    403 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    404 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    429 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    500 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    503 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
      |    504 | { "type": "#string", "message": "#string", "code": "#string" }                                                                                                                                                                                                                                |
