// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Post_setDesc_148780b2fa_Test {

    private Post post;

    @Before
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testSetDesc_Success() {
        String expectedDesc = "This is a test description";
        post.setDesc(expectedDesc);
        assertEquals(expectedDesc, post.getDesc());
    }

    @Test
    public void testSetDesc_Null() {
        post.setDesc(null);
        assertEquals(null, post.getDesc());
    }

    @Test
    public void testSetDesc_EmptyString() {
        post.setDesc("");
        assertEquals("", post.getDesc());
    }
}
