
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanVertex12533 using AI Type Vertex AI and AI Model claude-3-5-sonnet-v2

Test generated by RoostGPT for test amanVertex12533 using AI Type Vertex AI and AI Model claude-3-5-sonnet-v2

ROOST_METHOD_HASH=getExp_a80bcda041
ROOST_METHOD_SIG_HASH=getExp_e90c52dc7e


I'll help you create comprehensive test scenarios for the `getExp()` method based on the provided information.

```
Scenario 1: Verify Default Experience Value

Details:
  TestName: getDefaultExperienceValue
  Description: Validates that a newly created Post object returns the default experience value.
Execution:
  Arrange: Create a new Post object without setting any values
  Act: Call getExp() method
  Assert: Verify that the returned value is 0 (default value for int)
Validation:
  This test ensures that when a Post object is created without explicitly setting an experience value,
  the getExp() method returns the default integer value. This is important for maintaining consistent
  behavior when dealing with uninitialized Post objects.

Scenario 2: Verify Experience Value After Setting

Details:
  TestName: getExperienceAfterSetting
  Description: Validates that getExp() returns the correct value after using setExp()
Execution:
  Arrange: Create a Post object and set experience value using setExp(5)
  Act: Call getExp() method
  Assert: Verify that the returned value matches the set value (5)
Validation:
  This test verifies the basic getter-setter functionality for the exp field, ensuring that
  the value retrieved matches what was previously set. This is crucial for maintaining data integrity.

Scenario 3: Verify Experience Value With Maximum Integer

Details:
  TestName: getMaximumExperienceValue
  Description: Validates that getExp() correctly handles maximum integer value
Execution:
  Arrange: Create a Post object and set experience to Integer.MAX_VALUE
  Act: Call getExp() method
  Assert: Verify that the returned value equals Integer.MAX_VALUE
Validation:
  This test ensures that the getter can handle extreme values without overflow or data loss,
  which is important for system reliability when dealing with edge cases.

Scenario 4: Verify Experience Value With Minimum Integer

Details:
  TestName: getMinimumExperienceValue
  Description: Validates that getExp() correctly handles minimum integer value
Execution:
  Arrange: Create a Post object and set experience to Integer.MIN_VALUE
  Act: Call getExp() method
  Assert: Verify that the returned value equals Integer.MIN_VALUE
Validation:
  This test verifies that the getter can handle negative values and minimum integer bounds correctly,
  ensuring robust handling of all possible integer values.

Scenario 5: Verify Experience Value Consistency

Details:
  TestName: getExperienceValueConsistency
  Description: Validates that multiple calls to getExp() return consistent values
Execution:
  Arrange: Create a Post object and set experience value
  Act: Call getExp() multiple times
  Assert: Verify that all calls return the same value
Validation:
  This test ensures that the getter maintains consistency across multiple invocations,
  which is important for maintaining data reliability and preventing any unexpected value changes.
```

These test scenarios cover the main aspects of the `getExp()` method, including:
- Default value handling
- Basic functionality
- Edge cases (maximum and minimum integer values)
- Consistency of returned values

Each scenario focuses on a specific aspect of the method's behavior while staying within the constraints of the provided class structure and available methods.
*/

// ********RoostGPT********

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;

public class PostGetExpTest {

	private Post post;

	@BeforeEach
	void setUp() {
		post = new Post();
	}

	@Test
	@Tag("valid")
	public void testDefaultExperienceValue() {
		assertEquals(0, post.getExp());
	}

	@Test
	@Tag("valid")
	public void testExperienceAfterSetting() {
		post.setExp(5);
		assertEquals(5, post.getExp());
	}

	@Test
	@Tag("boundary")
	public void testMaximumExperienceValue() {
		post.setExp(Integer.MAX_VALUE);
		assertEquals(Integer.MAX_VALUE, post.getExp());
	}

	@Test
	@Tag("boundary")
	public void testMinimumExperienceValue() {
		post.setExp(Integer.MIN_VALUE);
		assertEquals(Integer.MIN_VALUE, post.getExp());
	}

	@Test
	@Tag("valid")
	public void testExperienceValueConsistency() {
		post.setExp(10);
		int firstCall = post.getExp();
		int secondCall = post.getExp();
		int thirdCall = post.getExp();

		assertEquals(firstCall, secondCall);
		assertEquals(secondCall, thirdCall);
	}

}