// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;

public class Post_toString_ceffa8036e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testToString() {
        post.setProfile("Software Engineer");
        post.setDesc("Responsible for software development");
        post.setExp(2);
        post.setTechs(new String[]{"Java", "Spring Boot", "MongoDB"});

        String expectedOutput = "Post{" +
                "profile='Software Engineer'" +
                ", desc='Responsible for software development'" +
                ", exp=2" +
                ", techs=" + Arrays.toString(new String[]{"Java", "Spring Boot", "MongoDB"}) +
                '}';

        Assertions.assertEquals(expectedOutput, post.toString());
    }

    @Test
    public void testToStringWithNoTechs() {
        post.setProfile("Software Engineer");
        post.setDesc("Responsible for software development");
        post.setExp(2);

        String expectedOutput = "Post{" +
                "profile='Software Engineer'" +
                ", desc='Responsible for software development'" +
                ", exp=2" +
                ", techs=null" +
                '}';

        Assertions.assertEquals(expectedOutput, post.toString());
    }
}
