// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.springframework.boot.test.context.SpringBootTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

@SpringBootTest
public class Post_getExp_e90c52dc7e_Test {

    @Test
    public void testGetExpPositiveScenario() {
        // TODO: Replace the argument with the correct expected experience
        int expectedExp = 5;

        JobPost jobPost = new JobPost();
        jobPost.setExp(expectedExp);

        int actualExp = jobPost.getExp();
        Assertions.assertEquals(expectedExp, actualExp, "The expected and actual experience didn't match");
    }

    @Test
    public void testGetExpNegativeScenario() {
        // TODO: Replace the argument with the correct expected experience
        int notExpectedExp = 10;

        JobPost jobPost = new JobPost();
        jobPost.setExp(5);

        int actualExp = jobPost.getExp();
        Assertions.assertNotEquals(notExpectedExp, actualExp, "The not expected and actual experience matched");
    }
}
