// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;

@SpringBootTest
public class Post_setTechs_1b061b0fa7_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        post = new Post();
    }

    @Test
    public void testSetTechs_success() {
        String[] expectedTechs = {"Java", "Spring Boot", "MongoDB"};
        post.setTechs(expectedTechs);
        assertArrayEquals(expectedTechs, post.getTechs());
    }

    @Test
    public void testSetTechs_emptyArray() {
        String[] expectedTechs = {};
        post.setTechs(expectedTechs);
        assertArrayEquals(expectedTechs, post.getTechs());
    }
}
