

// ********RoostGPT********
/*
Test generated by RoostGPT for test amanJava using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getExp_a80bcda041
ROOST_METHOD_SIG_HASH=getExp_e90c52dc7e

```plaintext
Scenario 1: Validate Default Value of 'exp' Field

Details:
  TestName: defaultValueOfExp
  Description: This test checks the default value of the 'exp' field to ensure it is initialized to zero.
Execution:
  Arrange: Create a Post object.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value is zero.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field is properly initialized and can be retrieved correctly using the getExp() method.

Scenario 2: Validate Setting and Getting 'exp' Field

Details:
  TestName: setAndGetExp
  Description: This test verifies that the 'exp' field can be set and retrieved correctly using the setExp() and getExp() methods.
Execution:
  Arrange: Create a Post object and set the 'exp' field to a specific value.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value matches the set value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field can be set and retrieved accurately, which is essential for the functionality of the Post class.

Scenario 3: Validate 'exp' Field with Maximum Integer Value

Details:
  TestName: maxIntegerValueOfExp
  Description: This test checks the behavior of the 'exp' field when set to the maximum integer value.
Execution:
  Arrange: Create a Post object and set the 'exp' field to Integer.MAX_VALUE.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value is Integer.MAX_VALUE.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field can handle the maximum integer value without issues.

Scenario 4: Validate 'exp' Field with Minimum Integer Value

Details:
  TestName: minIntegerValueOfExp
  Description: This test checks the behavior of the 'exp' field when set to the minimum integer value.
Execution:
  Arrange: Create a Post object and set the 'exp' field to Integer.MIN_VALUE.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value is Integer.MIN_VALUE.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field can handle the minimum integer value without issues.

Scenario 5: Validate 'exp' Field with Zero Value

Details:
  TestName: zeroValueOfExp
  Description: This test checks the behavior of the 'exp' field when set to zero.
Execution:
  Arrange: Create a Post object and set the 'exp' field to zero.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value is zero.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field can handle a zero value without issues.

Scenario 6: Validate 'exp' Field with Negative Integer Value

Details:
  TestName: negativeValueOfExp
  Description: This test checks the behavior of the 'exp' field when set to a negative integer value.
Execution:
  Arrange: Create a Post object and set the 'exp' field to a negative value.
  Act: Retrieve the value of 'exp' using the getExp() method.
  Assert: Verify that the retrieved value is the set negative value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  This test ensures that the 'exp' field can handle negative integer values without issues.

```
*/

// ********RoostGPT********

package com.telusko.joblisting.model;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;
import com.telusko.joblisting.model.Post;
import org.junit.jupiter.api.*;
import org.springframework.data.mongodb.core.mapping.Document;

public class PostGetExpTest {
    @Test
    @Tag("valid")
    public void testDefaultValueOfExp() {
        Post post = new Post();
        int actualExp = post.getExp();
        assertEquals(0, actualExp, "The default value of 'exp' should be zero.");
    }
    @Test
    @Tag("valid")
    public void testSetAndGetExp() {
        Post post = new Post();
        post.setExp(5);
        int actualExp = post.getExp();
        assertEquals(5, actualExp, "The value of 'exp' should be set and retrieved correctly.");
    }
    @Test
    @Tag("boundary")
    public void testMaxIntegerValueOfExp() {
        Post post = new Post();
        post.setExp(Integer.MAX_VALUE);
        int actualExp = post.getExp();
        assertEquals(Integer.MAX_VALUE, actualExp, "The 'exp' field should handle the maximum integer value.");
    }
    @Test
    @Tag("boundary")
    public void testMinIntegerValueOfExp() {
        Post post = new Post();
        post.setExp(Integer.MIN_VALUE);
        int actualExp = post.getExp();
        assertEquals(Integer.MIN_VALUE, actualExp, "The 'exp' field should handle the minimum integer value.");
    }
    @Test
    @Tag("valid")
    public void testZeroValueOfExp() {
        Post post = new Post();
        post.setExp(0);
        int actualExp = post.getExp();
        assertEquals(0, actualExp, "The 'exp' field should handle a zero value.");
    }
    @Test
    @Tag("invalid")
    public void testNegativeValueOfExp() {
        Post post = new Post();
        post.setExp(-5);
        int actualExp = post.getExp();
        assertEquals(-5, actualExp, "The 'exp' field should handle negative integer values.");
    }
}