// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Post_setProfile_50f29a11fe_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testSetProfileSuccess() {
        String expectedProfile = "Software Engineer";
        post.setProfile(expectedProfile);
        Assertions.assertEquals(expectedProfile, post.getProfile());
    }

    @Test
    public void testSetProfileFailure() {
        String expectedProfile = "";
        post.setProfile(expectedProfile);
        Assertions.assertNotEquals("Data Scientist", post.getProfile());
    }
}
