

// ********RoostGPT********
/*
Test generated by RoostGPT for test amanClaude19thMarch using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

Test generated by RoostGPT for test amanClaude19thMarch using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=getExp_a80bcda041
ROOST_METHOD_SIG_HASH=getExp_e90c52dc7e

I'll create test scenarios for the `getExp()` method based on the provided information and constraints.

```
Scenario 1: Verify Default Experience Value

Details:
  TestName: getDefaultExperienceValue
  Description: Validates that a newly created Post object returns the default experience value.
Execution:
  Arrange: Create a new Post object without setting any values
  Act: Call getExp() method on the Post object
  Assert: Verify that the returned value is 0 (default value for int)
Validation:
  This test ensures that when a Post object is created without explicitly setting an experience value, 
  the getExp() method returns the default integer value. This is important for maintaining data consistency 
  when new Post objects are created.

Scenario 2: Verify Set Experience Value

Details:
  TestName: getSetExperienceValue
  Description: Validates that getExp() returns the correct value after setting it using setExp()
Execution:
  Arrange: Create a Post object and set experience value using setExp(5)
  Act: Call getExp() method
  Assert: Verify that the returned value matches the set value (5)
Validation:
  This test verifies the basic getter-setter functionality for the exp field, ensuring that 
  the value retrieved matches what was previously set. This is crucial for maintaining data integrity.

Scenario 3: Verify Maximum Integer Value

Details:
  TestName: getMaximumExperienceValue
  Description: Validates that getExp() can handle the maximum possible integer value
Execution:
  Arrange: Create a Post object and set experience to Integer.MAX_VALUE using setExp()
  Act: Call getExp() method
  Assert: Verify that the returned value equals Integer.MAX_VALUE
Validation:
  This test ensures that the getExp() method can handle extreme values without overflow or data loss, 
  which is important for system reliability when dealing with edge cases.

Scenario 4: Verify Negative Experience Value

Details:
  TestName: getNegativeExperienceValue
  Description: Validates that getExp() correctly returns negative experience values
Execution:
  Arrange: Create a Post object and set a negative experience value using setExp(-1)
  Act: Call getExp() method
  Assert: Verify that the returned value is -1
Validation:
  This test verifies that the method can handle negative values correctly, which might be important 
  for error conditions or special cases in the application logic.

Scenario 5: Verify Experience Value After Multiple Updates

Details:
  TestName: getExperienceValueAfterMultipleUpdates
  Description: Validates that getExp() returns the most recent value after multiple setExp() calls
Execution:
  Arrange: Create a Post object and set experience multiple times (e.g., 1, 2, 3)
  Act: Call getExp() method
  Assert: Verify that the returned value matches the last set value (3)
Validation:
  This test ensures that the getter consistently returns the most recently set value, 
  which is crucial for maintaining data consistency when the experience value is updated multiple times.
```

These test scenarios cover the main functionality of the `getExp()` method, including:
- Default value behavior
- Basic getter functionality
- Edge cases (maximum integer value)
- Negative values
- Multiple updates

Each scenario uses only the methods and fields that were explicitly provided in the original class definition. The scenarios focus on testing the `getExp()` method while utilizing the available `setExp()` method for setup purposes.,
*/

// ********RoostGPT********

package com.telusko.joblisting.model;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;

public class PostGetExpTest {
    @Test
    @Tag("valid")
    public void getDefaultExperienceValue() {
        Post post = new Post();
        assertEquals(0, post.getExp());
    }
    @Test
    @Tag("valid") 
    public void getSetExperienceValue() {
        Post post = new Post();
        post.setExp(5);
        assertEquals(5, post.getExp());
    }
    @Test
    @Tag("boundary")
    public void getMaximumExperienceValue() {
        Post post = new Post();
        post.setExp(Integer.MAX_VALUE);
        assertEquals(Integer.MAX_VALUE, post.getExp());
    }
    @Test
    @Tag("invalid")
    public void getNegativeExperienceValue() {
        Post post = new Post();
        post.setExp(-1);
        assertEquals(-1, post.getExp());
    }
    @Test
    @Tag("valid")
    public void getExperienceValueAfterMultipleUpdates() {
        Post post = new Post();
        post.setExp(1);
        post.setExp(2);
        post.setExp(3);
        assertEquals(3, post.getExp());
    }
}