// Test generated by RoostGPT for test aman-sampletest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;

public class Post_getTechs_443a51e600_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testGetTechsWhenTechsAreSet() {
        String[] techs = {"Java", "Spring", "Hibernate"};
        post.setTechs(techs);

        assertArrayEquals(techs, post.getTechs(), "Techs should match the ones set in the post");
    }

    @Test
    public void testGetTechsWhenTechsAreNotSet() {
        assertNull(post.getTechs(), "Techs should be null when they are not set in the post");
    }
}
