// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Post_toString_ceffa8036e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
        post.setProfile("Software Developer");
        post.setDesc("Develop and maintain software applications");
        post.setExp(2);
        post.setTechs(new String[]{"Java", "Spring Boot"});
    }

    @Test
    public void testToString() {
        String expected = "Post{" +
                "profile='Software Developer'" +
                ", desc='Develop and maintain software applications'" +
                ", exp=2" +
                ", techs=" + Arrays.toString(new String[]{"Java", "Spring Boot"}) +
                '}';
        assertEquals(expected, post.toString());
    }

    @Test
    public void testToStringWithDifferentValues() {
        post.setProfile("Data Analyst");
        post.setDesc("Analyze and interpret complex data sets");
        post.setExp(3);
        post.setTechs(new String[]{"Python", "SQL"});
        String expected = "Post{" +
                "profile='Data Analyst'" +
                ", desc='Analyze and interpret complex data sets'" +
                ", exp=3" +
                ", techs=" + Arrays.toString(new String[]{"Python", "SQL"}) +
                '}';
        assertEquals(expected, post.toString());
    }
}
