// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Post_getProfile_ce58a7beef_Test {

    @Autowired
    private Post post;

    @Test
    public void testGetProfile_Success() {
        post.setProfile("Software Developer");
        String profile = post.getProfile();
        assertEquals("Software Developer", profile);
    }

    @Test
    public void testGetProfile_Null() {
        post.setProfile(null);
        String profile = post.getProfile();
        assertNull(profile);
    }
}
