// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_setProfile_50f29a11fe_Test {

    @InjectMocks
    private Post post;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetProfileSuccess() {
        String profile = "Software Engineer";
        post.setProfile(profile);
        Assertions.assertEquals(profile, post.getProfile(), "Profile should be set correctly");
    }

    @Test
    public void testSetProfileWithEmptyString() {
        String profile = "";
        post.setProfile(profile);
        Assertions.assertEquals(profile, post.getProfile(), "Profile should be set even if it is empty");
    }

    @Test
    public void testSetProfileWithNull() {
        String profile = null;
        post.setProfile(profile);
        Assertions.assertNull(post.getProfile(), "Profile should be null if set with null value");
    }
}
