// Test generated by RoostGPT for test aman-sampletest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Post_setExp_4638d82240_Test {
    
    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testSetExp_Positive() {
        int exp = 5;
        post.setExp(exp);
        assertEquals(exp, post.getExp(), "Expected experience doesn't match with actual experience");
    }

    @Test
    public void testSetExp_Negative() {
        int exp = -1;
        post.setExp(exp);
        assertEquals(exp, post.getExp(), "Expected experience doesn't match with actual experience");
    }

    @Test
    public void testSetExp_Zero() {
        int exp = 0;
        post.setExp(exp);
        assertEquals(exp, post.getExp(), "Expected experience doesn't match with actual experience");
    }
}
