// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Post_getDesc_66e632b9da_Test {

    @Autowired
    private Post post;
    
    @MockBean
    private ExternalService externalService;

    @Test
    public void testGetDescSuccess() {
        String expectedDesc = "Job Description";
        // TODO: Replace "Job Description" with the actual description you want to test

        when(externalService.getDesc()).thenReturn(expectedDesc);
        String actualDesc = post.getDesc();
        
        assertEquals(expectedDesc, actualDesc);
    }

    @Test
    public void testGetDescFailure() {
        String expectedDesc = "Job Description";
        // TODO: Replace "Job Description" with the actual description you want to test

        when(externalService.getDesc()).thenReturn("Incorrect Description");
        String actualDesc = post.getDesc();

        assertNotEquals(expectedDesc, actualDesc);
    }
}
