// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Post_getTechs_443a51e600_Test {

    @InjectMocks
    private Post post;

    @Before
    public void init() {
        MockitoAnnotations.initMocks(this);
        post.setTechs(new String[]{"Java", "Spring Boot", "MongoDB"});
    }

    @Test
    public void testGetTechs_Success() {
        String[] expectedTechs = {"Java", "Spring Boot", "MongoDB"};
        Assert.assertArrayEquals(expectedTechs, post.getTechs());
    }

    @Test
    public void testGetTechs_Failure() {
        String[] unexpectedTechs = {"Python", "Django", "PostgreSQL"};
        Assert.assertNotEquals(Arrays.toString(unexpectedTechs), Arrays.toString(post.getTechs()));
    }
}
