// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.mongodb.core.mapping.Document;

@SpringBootTest
public class Post_Post_ec8a5320eb_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testPostCreation() {
        assertEquals(Post.class, post.getClass());
    }

    @Test
    public void testPostFields() {
        post.setId("12345");
        post.setTitle("Test Title");
        post.setDescription("Test Description");

        assertEquals("12345", post.getId());
        assertEquals("Test Title", post.getTitle());
        assertEquals("Test Description", post.getDescription());
    }
}
