// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class Post_getTechs_443a51e600_Test {

    @InjectMocks
    private Post post;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetTechs_success() {
        String[] expectedTechs = {"Java", "Spring Boot", "MongoDB"};
        post.setTechs(expectedTechs);
        String[] actualTechs = post.getTechs();
        assertArrayEquals(expectedTechs, actualTechs);
    }

    @Test
    public void testGetTechs_null() {
        String[] expectedTechs = null;
        post.setTechs(expectedTechs);
        String[] actualTechs = post.getTechs();
        assertArrayEquals(expectedTechs, actualTechs);
    }
}
