// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_setTechs_1b061b0fa7_Test {
    
    @Test
    public void testSetTechs() {
        Post post = new Post();
        String[] techs = {"Java", "Spring Boot", "MongoDB"};
        post.setTechs(techs);

        assertArrayEquals(techs, post.getTechs(), "The method did not set the techs correctly");
    }

    @Test
    public void testSetTechsWithNull() {
        Post post = new Post();
        post.setTechs(null);

        assertNull(post.getTechs(), "The method did not handle null input correctly");
    }

    @Test
    public void testSetTechsWithEmptyArray() {
        Post post = new Post();
        String[] techs = {};
        post.setTechs(techs);

        assertArrayEquals(techs, post.getTechs(), "The method did not handle empty array correctly");
    }
}
