// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_getProfile_ce58a7beef_Test {

    @Test
    public void testGetProfile() {
        Post post = new Post();
        post.setProfile("Software Engineer");
        assertEquals("Software Engineer", post.getProfile());
    }

    @Test
    public void testGetProfile_Empty() {
        Post post = new Post();
        post.setProfile("");
        assertEquals("", post.getProfile());
    }
}
