// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;

public class Post_Post_ec8a5320eb_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testPostConstructor() {
        assertTrue(post instanceof Post);
    }

    @Test
    public void testPostConstructorWithParameters() {
        Post post = new Post("Title", "Description");
        assertEquals("Title", post.getTitle());
        assertEquals("Description", post.getDescription());
    }
}
