// Test generated by RoostGPT for test aman-sampletest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.*;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.junit.MockitoJUnitRunner;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;
import static org.mockito.MockitoAnnotations.initMocks;

@RunWith(MockitoJUnitRunner.class)
@EnableSwagger2
class JoblistingApplication_api_24e94226d8_Test {

    @InjectMocks
    private JoblistingApplication joblistingApplication;

    @BeforeEach
    void setUp() {
        initMocks(this);
    }

    @Test
    public void testApi() {
        Docket result = joblistingApplication.api();
        assertNotNull(result);
        Assertions.assertEquals(DocumentationType.SWAGGER_2, result.getDocumentationType());
    }

    @Test
    public void testApiWithException() {
        when(joblistingApplication.api()).thenThrow(new RuntimeException("Test exception"));
        Assertions.assertThrows(RuntimeException.class, () -> joblistingApplication.api());
    }
}
