
// ********RoostGPT********
/*
Test generated by RoostGPT for test test-name-pvt1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test test-name-pvt1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=apiInfo_b15996cb2b
ROOST_METHOD_SIG_HASH=apiInfo_95b025c193

Scenario 1: Validate the construction of ApiInfo object

  Details:
    TestName: testBuildApiInfo
    Description: This test must verify that the apiInfo method correctly initializes and returns an ApiInfo object.
  Execution:
    Arrange: There is no data to arrange.
    Act: Call the apiInfo method.
    Assert: Use assertNotNull to confirm that the method does not return a null object.
  Validation:
    The aim of this assertion is to confirm that the method successfully creates an ApiInfo object. Returning a null object can indicate that there was a problem during the initialization process. This test is crucial for ensuring that the application correctly constructs its API documentation.

Scenario 2: Check the default values in the constructed ApiInfo object

  Details:
    TestName: testDefaultApiInfoValues
    Description: This test checks that the default values in the ApiInfo object are as expected.
  Execution:
    Arrange: No pre-conditions
    Act: Call the apiInfo method and get the resulting ApiInfo object.
    Assert: Use the getter methods of the ApiInfo object to assertEqual that the default values (e.g., title, version, etc) are as expected.
  Validation:
    The assertion is checking that the values in the ApiInfo object have been correctly set to their default values. This is to ensure the API documentation has the correct information when no specific information has been set in the builder.

Scenario 3: Validate the immutability of ApiInfo object

  Details:
    TestName: testApiInfoObjectImmutability
    Description: This test checks that the ApiInfo object returned from the method is immutable.
  Execution:
    Arrange: No pre-conditions
    Act: Call the apiInfo method and get the resulting ApiInfo object, then attempt to alter one of the object’s fields (e.g., title, version, etc).
    Assert: Use assertThrows to confirm that the operation throws an UnsupportedOperationException.
  Validation:
    This assertion confirms that the ApiInfo object is immutable. This confirms that the object cannot be modified once constructed which is important for the integrity of API documentation.

*/

// ********RoostGPT********
package com.telusko.joblisting;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RestController;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

public class JoblistingApplicationApiInfoTest {

	private JoblistingApplication joblistingApp = new JoblistingApplication();

	@Test
	@Tag("valid")
	void testBuildApiInfo() {
		ApiInfo apiInfo = joblistingApp.apiInfo();
		assertNotNull(apiInfo);
	}

	@Test
	@Tag("boundary")
	void testDefaultApiInfoValues() {
		ApiInfo apiInfo = joblistingApp.apiInfo();
		assertEquals("", apiInfo.getTitle());
		assertEquals("", apiInfo.getDescription());
		assertEquals("", apiInfo.getVersion());
	}
	// Removed the testApiInfoObjectImmutability test case as getExtensions() method is
	// not existent in the ApiInfo class.

}