/*
Test generated by RoostGPT for test aman321 using AI Type Open AI and AI Model gpt-4

1. Test Scenario: Validate if the API documentation is enabled and functioning correctly by checking if the Docket bean is created and the Swagger documentation type is set to SWAGGER_2.

2. Test Scenario: Check if the API is correctly selecting all APIs with the RestController annotation for documentation. 

3. Test Scenario: Validate if the API documentation includes routes from all paths by checking if PathSelectors.any() is working as expected.

4. Test Scenario: Check if the API info is correctly being built and attached to the Docket object by calling the apiInfo() method.

5. Test Scenario: Validate if the API is correctly disabling default response messages by checking if useDefaultResponseMessages(false) is functioning as expected.

6. Test Scenario: Test if the API is correctly selecting all the APIs from base package for documentation.

7. Test Scenario: Check if the API documentation provides correct and expected information when the API is run.

8. Test Scenario: Validate if the API documentation correctly updates when changes are made to the API, ensuring that the Docket bean is correctly reinitialized.

9. Test Scenario: Check if the API documentation is accessible and readable, validating the user interface of the documentation.

10. Test Scenario: Validate if the API is correctly handling errors and providing appropriate error messages in the documentation.
*/
package com.telusko.joblisting;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import springfox.documentation.service.ApiInfo;
import org.springframework.boot.SpringApplication;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@EnableSwagger2
public class JoblistingApplication_api_24e94226d8_Test {

    @InjectMocks
    JoblistingApplication joblistingApplication;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testApi() {
        Docket docket = joblistingApplication.api();
        assertNotNull(docket);
        assertEquals(DocumentationType.SWAGGER_2, docket.getDocumentationType());
    }

    @Test
    public void testApiInfo() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        assertNotNull(apiInfo);
    }

    @Test
    public void testMain() {
        String[] args = new String[] {"args1", "args2"};
        JoblistingApplication.main(args);
        verifyStatic(SpringApplication.class);
        SpringApplication.run(JoblistingApplication.class, args);
    }
}
