// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

@EnableSwagger2
@SpringBootTest
public class JoblistingApplication_api_24e94226d8_Test {

    @MockBean
    private JoblistingApplication joblistingApplication;

    @Test
    public void testApi() {
        when(joblistingApplication.api()).thenReturn(new Docket(DocumentationType.SWAGGER_2));
        Docket result = joblistingApplication.api();
        assertNotNull(result);
    }

    @Test
    public void testApiWithNull() {
        when(joblistingApplication.api()).thenReturn(null);
        Docket result = joblistingApplication.api();
        assertNotNull(result, "API Docket should not be null");
    }
}
