/*
Test generated by RoostGPT for test aman321 using AI Type Open AI and AI Model gpt-4

Test Scenario 1: Test to check if the `apiInfo()` method returns a non-null object.
- Description: This test will check if the `apiInfo()` method returns a non-null `ApiInfo` object. The test will fail if the method returns null.

Test Scenario 2: Test to check if the `apiInfo()` method returns an instance of `ApiInfo`.
- Description: This test will check if the returned object from the `apiInfo()` method is an instance of `ApiInfo`. The test will fail if the returned object is not an instance of `ApiInfo`.

Test Scenario 3: Test to check if the `apiInfo()` method returns a builder with default values.
- Description: This test will check if the `ApiInfoBuilder` has all its properties set to the default values. The test will fail if any property of the `ApiInfoBuilder` is not set to its default value.

Test Scenario 4: Test to check if the `apiInfo()` method returns an `ApiInfo` object with unset properties.
- Description: This test will check if the `ApiInfo` object has all its properties unset. The test will fail if any property of the `ApiInfo` is set.

Test Scenario 5: Test to check if the `apiInfo()` method returns an `ApiInfo` object with a null `ApiInfoBuilder`.
- Description: This test will check if the `ApiInfoBuilder` object is null. The test will fail if the `ApiInfoBuilder` object is not null.

Test Scenario 6: Test to check if the `apiInfo()` method returns an `ApiInfo` object when the `ApiInfoBuilder` object is modified.
- Description: This test will check if the `ApiInfo` object is returned when the `ApiInfoBuilder` object is modified. The test will fail if the `ApiInfo` object is not returned or if the modifications to the `ApiInfoBuilder` object are not reflected in the `ApiInfo` object.
*/
package com.telusko.joblisting;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import springfox.documentation.service.ApiInfo;

import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class JoblistingApplication_apiInfo_0779216cdc_Test {

    @Autowired
    private JoblistingApplication joblistingApplication;

    @Test
    public void testApiInfoNotNull() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        assertNotNull("ApiInfo object should not be null", apiInfo);
    }

    @Test
    public void testApiInfoInstance() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        assertTrue("ApiInfo object should be an instance of ApiInfo", apiInfo instanceof ApiInfo);
    }

    @Test
    public void testApiInfoBuilderDefaultValues() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        // TODO: Check if all properties of the ApiInfo object are set to their default values
        // This is dependent on the default values of the properties of the ApiInfo object
    }

    @Test
    public void testApiInfoUnsetProperties() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        // TODO: Check if all properties of the ApiInfo object are unset
        // This is dependent on the properties of the ApiInfo object
    }

    @Test
    public void testApiInfoNullBuilder() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        // TODO: Check if the ApiInfo object has a null ApiInfoBuilder
        // This is dependent on the implementation of the ApiInfo object
    }

    @Test
    public void testApiInfoModifiedBuilder() {
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        // TODO: Check if the ApiInfo object is returned when the ApiInfoBuilder object is modified
        // This is dependent on the implementation of the ApiInfo object and ApiInfoBuilder object
    }
}
