
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanScope using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test amanScope using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=apiInfo_b15996cb2b
ROOST_METHOD_SIG_HASH=apiInfo_95b025c193

"""
Scenario 1: Valid ApiInfo Object Construction Test

Details:
  TestName: validApiInfoConstructionTest
  Description: The test will verify the correctness of the ApiInfo object creation through apiInfo() method. Specifically, it will check if the object is correctly instantiated and has the default values.
Execution:
  Arrange: No arrangement needed as no external input or resource is required by the method.
  Act: Invoke apiInfo() method.
  Assert: Use JUnit assertions to ascertain that the returned object of type ApiInfo is not null.
Validation:
  The assertion aims to verify that the ApiInfo object creation process is working as expected. The successful creation of the default ApiInfo object is crucial for the Swagger for identifying and documenting microservices.

Scenario 2: Check Default Value of ApiInfo Object

Details:
  TestName: checkDefaultValueOfApiInfoObjectTest
  Description: Test is meant to scrutinize if the ApiInfo object has default values upon creation through apiInfo() method.
Execution:
  Arrange: No arrangement needed as no external input or resource required by the method.
  Act: Invoke apiInfo() method.
  Assert: Use JUnit assertions to check that title, description, version, termsOfServiceUrl, license, licenseUrl, and contact of the returned ApiInfo object are all empty.
Validation:
  As the ApiInfoBuilder.build() without any set values builds a default ApiInfo object with empty fields, the significance of the test is to ensure the correct behavior of the apiInfo() method.

Scenario 3: Repetition ApiInfo Object Construction Test

Details:
  TestName: repetitionApiInfoConstructionTest
  Description: This test repeats the construction of ApiInfo object numerous times to ensure the consistency of the apiInfo() method.
Execution:
  Arrange: No initial arrangement is required.
  Act: Repeatedly invoke apiInfo() method for a certain times, for example 1000 times.
  Assert: Apply JUnit assertions to confirm that all returned ApiInfo objects are not null.
Validation:
  The purpose of the test is to verify the stability and consistency of apiInfo() method, which is an essential part for the robustness of the system.
"""
*/

// ********RoostGPT********
package com.telusko.joblisting;

import org.junit.jupiter.api.*;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RestController;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import static org.junit.jupiter.api.Assertions.*;

@org.junit.jupiter.api.Tag("Valid")
public class JoblistingApplicationApiInfoTest {

	@Test
	public void validApiInfoConstructionTest() {
		JoblistingApplication joblistingApplication = new JoblistingApplication();

		ApiInfo apiInfo = joblistingApplication.apiInfo();

		assertNotNull(apiInfo, "ApiInfo construction failed. The object is null.");
	}

	@Test
	public void checkDefaultValueOfApiInfoObjectTest() {
		JoblistingApplication joblistingApplication = new JoblistingApplication();

		ApiInfo apiInfo = joblistingApplication.apiInfo();

		assertAll("Check all default values in ApiInfo object",
				() -> assertEquals("", apiInfo.getTitle(), "Default title in ApiInfo object is not empty."),
				() -> assertEquals("", apiInfo.getDescription(), "Default description in ApiInfo object is not empty."),
				() -> assertEquals("", apiInfo.getVersion(), "Default version in ApiInfo object is not empty."),
				() -> assertEquals("", apiInfo.getTermsOfServiceUrl(),
						"Default termsOfServiceUrl in ApiInfo object is not empty."),
				() -> assertEquals("", apiInfo.getLicense(), "Default license in ApiInfo object is not empty."),
				() -> assertEquals("", apiInfo.getLicenseUrl(), "Default licenseUrl in ApiInfo object is not empty."),
				() -> assertNull(apiInfo.getContact(), "Default contact in ApiInfo object is not null."));
	}

	@RepeatedTest(1000)
	public void repetitionApiInfoConstructionTest() {
		JoblistingApplication joblistingApplication = new JoblistingApplication();

		ApiInfo apiInfo = joblistingApplication.apiInfo();

		assertNotNull(apiInfo, "Repeated ApiInfo construction failed. The object is null.");
	}

}