// Test generated by RoostGPT for test aman-sampletest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.builders.ApiInfoBuilder;

@SpringBootApplication
public class JoblistingApplication_apiInfo_0779216cdc_Test {

    @Test
    public void testApiInfoReturnsNotNull() {
        JoblistingApplication joblistingApplication = new JoblistingApplication();
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        Assertions.assertNotNull(apiInfo);
    }

    @Test
    public void testApiInfoReturnsCorrectInstance() {
        JoblistingApplication joblistingApplication = new JoblistingApplication();
        ApiInfo apiInfo = joblistingApplication.apiInfo();
        Assertions.assertTrue(apiInfo instanceof ApiInfo);
    }
}
